name: Deploy to Production

# Surveillant master baranch
on:
  push:
    branches: [ master ]

jobs:
  # To build docker image
  build:
    name: Build image
    runs-on: ubuntu-latest #GitHub上でホストされているubuntuで処理が実行される
    strategy:
      max-parallel: 4
    permissions:
      id-token: write
      contents: read


    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    # configure AWS Credentials using aws IAM
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/identity-providers-github-actions
        aws-region: ap-northeast-1

    # Login to Amazon ECR, then build, tag, and push a Docker image:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: moviefun
        IMAGE_TAG: ${{ github.sha }}
      # Build a docker container and
      # push it to ECR so that it can
      # be deployed to ECS.
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"
    
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/task-definition.json
        container-name: moviefun
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: moviefun
        cluster: moviefun
        wait-for-service-stability: true
        